[build]
  command = "npx @11ty/eleventy"
  publish = "dist"

[dev]
  command = "npx @11ty/eleventy --serve"
  port = 8080
  publish = "dist"

# Redirects (optional)
# [[redirects]]
#   from = "/old-path"
#   to = "/new-path"
#   status = 301

# Headers (optional)
# [[headers]]
#   for = "/*"
#   [headers.values]
# #   X-Frame-Options = "DENY"
# #   X-XSS-Protection = "1; mode=block"
# #   X-Content-Type-Options = "nosniff"
# #   Referrer-Policy = "strict-origin-when-cross-origin"
